### ISSUE TITLE
Recommend text centering / center labels

### ISSUE THREAD

**Issue by SevereOverfl0w** [milo-minderbinder/AWS-PlantUML#19]
The router looks strange without:

```
skinparam defaultTextAlignment center
```

Test by commenting out that line here:

http://www.plantuml.com/plantuml/uml/bP1DImCn48Rl-HLf3sAXsr1w43r8b-91i7RfjWfUIdPtseOcasKoGUclD_rI3thmaFdWdUVDCEF0cZWwAyBEOAj9Ezd0MaVB2_ZWt9eDEa2MTGf0GdIIQX1a_beMo-cJt3AtuKufqk-3ZU5jh680gdsQHXxKtYbdhC-SmGQeEaQLsAom6ZaPA08BEe0QtcJ3R7Yh6XDOT0pMDZOGoLv-KidBUHoqXsL_qqlsf3UWSgVt7ilHL_4Ff8hr3lYS_kOcthMHBznBCL7aKq_dT095FitVPi_bw3gCLkPmFTIs9oQpQR5SFAnEQc9NyrdgvuUfT7z6eBxiFafhTY2PjC4WhUSWhuwfBzVUoqfJUljkJ_pmbbbsBxzTn1YmIOjy0W00

It might be a good idea to always center the labels somehow to prevent this, or generally recommend this attribute be turned on in uml docs.

**Comment by milo-minderbinder** [comment]
Thanks!

Hmm, I'll have to think about this one a little bit. I definitely agree that in your specific example things look odd without the `skinparam` directive to force the text alignment, but I also want to make sure that the project doesn't get too prescriptive about formatting and general usage, or force people into changing their diagrams to fit the project. In your example, I might just suggest breaking up long labels into multiple lines (like the stereotype names are already) by inserting a few strategic `\r`'s or `\n`'s into the label as preferred. But I'll see if I can't figure out a more elegant way to fit most use cases. Open to any ideas!

**Comment by SevereOverfl0w** [comment]
I agree, it's something to think about.

**Comment by milo-minderbinder** [comment]
long time coming, but fixed in latest release
