### ISSUE TITLE
I use absolute path or relative path to dist folder still it doesn't work

### ISSUE THREAD

**Issue by IamGabrielWu** [milo-minderbinder/AWS-PlantUML#24]
This is my code. 
And my path for dist as below.
I tried use relative path like "!define AWSPUML ../dist" doesn't work.
Does it support path like this ?

`
@startuml
!define AWSPUML /Users/gwu/gitspace/AWS-PlantUML/dist

!includeurl AWSPUML/common.puml
!includeurl AWSPUML/ApplicationServices/AmazonAPIGateway/AmazonAPIGateway.puml
!includeurl AWSPUML/Compute/AWSLambda/AWSLambda.puml
!includeurl AWSPUML/Compute/AWSLambda/LambdaFunction/LambdaFunction.puml
!includeurl AWSPUML/Database/AmazonDynamoDB/AmazonDynamoDB.puml
!includeurl AWSPUML/Database/AmazonDynamoDB/table/table.puml
!includeurl AWSPUML/General/AWScloud/AWScloud.puml
!includeurl AWSPUML/General/client/client.puml
!includeurl AWSPUML/General/user/user.puml
!includeurl AWSPUML/SDKs/JavaScript/JavaScript.puml
!includeurl AWSPUML/Storage/AmazonS3/AmazonS3.puml
!includeurl AWSPUML/Storage/AmazonS3/bucket/bucket.puml

skinparam componentArrowColor Black
skinparam componentBackgroundColor White
skinparam nodeBackgroundColor White
skinparam agentBackgroundColor White
skinparam artifactBackgroundColor White

USER(user)
CLIENT(browser)
JAVASCRIPT(js,SDK)

AWSCLOUD(aws) {

    AMAZONS3(s3) {
        BUCKET(site,www.insecurity.co)
        BUCKET(logs,logs.insecurity.co)
    }

    AMAZONAPIGATEWAY(api)

    AWSLAMBDA(lambda) {
        LAMBDAFUNCTION(addComments,addComments)
    }

    AMAZONDYNAMODB(dynamo) {
        TABLE(comments,Comments)
    }
}

user - browser

browser -d-> site :**1a**) get\nstatic\ncontent
site ~> logs :1a
site .u.> browser :**1b**
browser - js
js -r-> comments :**2a**) get\ncomments
comments ..> js :**2b**

js -r-> api :**3**) add\ncomment

api -d-> addComments :**4**

addComments -> comments :**5**

comments ..> js :**6**) new\ncomments
@enduml
`

**Comment by milo-minderbinder** [comment]
hi @IamGabrielWu, thanks for your interest in the project. You can definitely use absolute or relative paths like you're describing, you just need to change you `includeurl` directives to `include` since you're trying to load the files from the local filesystem, and not from a remote URL.

e.g.:
```
@startuml

!define AWSPUML /Users/gwu/gitspace/AWS-PlantUML/dist

!include AWSPUML/common.puml
!include AWSPUML/ApplicationServices/AmazonAPIGateway/AmazonAPIGateway.puml
!include AWSPUML/Compute/AWSLambda/AWSLambda.puml
!include AWSPUML/Compute/AWSLambda/LambdaFunction/LambdaFunction.puml
!include AWSPUML/Database/AmazonDynamoDB/AmazonDynamoDB.puml
!include AWSPUML/Database/AmazonDynamoDB/table/table.puml
!include AWSPUML/General/AWScloud/AWScloud.puml
!include AWSPUML/General/client/client.puml
!include AWSPUML/General/user/user.puml
!include AWSPUML/SDKs/JavaScript/JavaScript.puml
!include AWSPUML/Storage/AmazonS3/AmazonS3.puml
!include AWSPUML/Storage/AmazonS3/bucket/bucket.puml
```

It's also worth noting that AWS-PlantUML is now part of the stdlib and comes bundled with PlantUML in recent release (see info [here](https://github.com/plantuml/plantuml-stdlib), so if you don't need to generate your own custom macros and sprites using the puml.py script, that may be an even easier option :-)

**Comment by IamGabrielWu** [comment]
@milo-minderbinder yep this is really awesome project i like it.  And the stdlib, can i generate my own icons with it ? for example, i need to create a jenkins icon and is it feasible to use stdlib ?

**Comment by milo-minderbinder** [comment]
Nope - you can only generate your own icon set if you clone this project and run the `puml.py` script yourself to generate the sprites & macros using your custom images (for jenkins, in your example). The stdlib only includes the pre-generated puml files that I create (basically, it just includes the contents of this project's `dist` directory, along with the dist of a couple similar projects).

**Comment by milo-minderbinder** [comment]
closed the issue since that answered your original question, but feel free to message me with other questions.
